"""Distance_metro2

Revision ID: 4dab045294b7
Revises: 972412aeff60
Create Date: 2024-03-23 22:43:32.445441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dab045294b7'
down_revision = '972412aeff60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Distance_metro_id_poe_poi_data', 'Distance_metro', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Distance_metro_id_poe_reality_data'), 'Distance_metro', 'reality_data', ['id_poe'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Distance_metro_id_poe_reality_data'), 'Distance_metro', type_='foreignkey')
    op.create_foreign_key('fk_Distance_metro_id_poe_poi_data', 'Distance_metro', 'poi_data', ['id_poe'], ['id'])
    # ### end Alembic commands ###
