"""Distance_attract3

Revision ID: 65724de867c3
Revises: 85d0025c6684
Create Date: 2024-03-23 23:20:54.057958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65724de867c3'
down_revision = '85d0025c6684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Distance_attraction', sa.Column('id_attraction', sa.Integer(), nullable=False))
    op.add_column('Distance_attraction', sa.Column('id_reality', sa.Integer(), nullable=False))
    op.drop_constraint('fk_Distance_attraction_id_metro_tourist_attractions', 'Distance_attraction', type_='foreignkey')
    op.drop_constraint('fk_Distance_attraction_id_poe_reality_data', 'Distance_attraction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Distance_attraction_id_reality_reality_data'), 'Distance_attraction', 'reality_data', ['id_reality'], ['id'])
    op.create_foreign_key(op.f('fk_Distance_attraction_id_attraction_tourist_attractions'), 'Distance_attraction', 'tourist_attractions', ['id_attraction'], ['id'])
    op.drop_column('Distance_attraction', 'id_metro')
    op.drop_column('Distance_attraction', 'id_poe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Distance_attraction', sa.Column('id_poe', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Distance_attraction', sa.Column('id_metro', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_Distance_attraction_id_attraction_tourist_attractions'), 'Distance_attraction', type_='foreignkey')
    op.drop_constraint(op.f('fk_Distance_attraction_id_reality_reality_data'), 'Distance_attraction', type_='foreignkey')
    op.create_foreign_key('fk_Distance_attraction_id_poe_reality_data', 'Distance_attraction', 'reality_data', ['id_poe'], ['id'])
    op.create_foreign_key('fk_Distance_attraction_id_metro_tourist_attractions', 'Distance_attraction', 'tourist_attractions', ['id_metro'], ['id'])
    op.drop_column('Distance_attraction', 'id_reality')
    op.drop_column('Distance_attraction', 'id_attraction')
    # ### end Alembic commands ###
