"""Reality

Revision ID: 6e794971bbbe
Revises: 6cf6fa3df435
Create Date: 2024-03-23 14:34:25.848018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e794971bbbe'
down_revision = '6cf6fa3df435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
