"""Tourist_attractions2

Revision ID: 85d0025c6684
Revises: 4dab045294b7
Create Date: 2024-03-23 22:59:53.181772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d0025c6684'
down_revision = '4dab045294b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Distance_attraction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_poe', sa.Integer(), nullable=False),
    sa.Column('id_metro', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_metro'], ['tourist_attractions.id'], name=op.f('fk_Distance_attraction_id_metro_tourist_attractions')),
    sa.ForeignKeyConstraint(['id_poe'], ['reality_data.id'], name=op.f('fk_Distance_attraction_id_poe_reality_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Distance_attraction'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Distance_attraction')
    # ### end Alembic commands ###
