"""Distance_metro

Revision ID: 972412aeff60
Revises: 4b47f003994f
Create Date: 2024-03-23 21:22:29.806955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972412aeff60'
down_revision = '4b47f003994f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Distance_metro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_poe', sa.Integer(), nullable=False),
    sa.Column('id_metro', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_metro'], ['metroStation.id'], name=op.f('fk_Distance_metro_id_metro_metroStation')),
    sa.ForeignKeyConstraint(['id_poe'], ['poi_data.id'], name=op.f('fk_Distance_metro_id_poe_poi_data')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Distance_metro'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Distance_metro')
    # ### end Alembic commands ###
