"""MetroStation

Revision ID: 974429b8933e
Revises: 6e794971bbbe
Create Date: 2024-03-23 14:58:47.712413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974429b8933e'
down_revision = '6e794971bbbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metroStation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hex_color', sa.String(), nullable=True),
    sa.Column('name_line', sa.String(), nullable=True),
    sa.Column('name_station', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metroStation'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metroStation')
    # ### end Alembic commands ###
